version: '3'

services:
  postgres:
    restart: always
    image: postgres:9.6.10-alpine
    container_name: dbContainer
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: stmdb
    ports:
      - '5433:5432'
    volumes:
      - database:/var/lib/postgresql

  python:
    restart: always
    build:
      context: ./
      dockerfile: PythonDockerfile
    entrypoint: /entrypoint.sh
    container_name: tmsBackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
    - postgres
    environment:
    - PYTHONUNBUFFERED=0

volumes:
  database:

