# Generated by Django 2.0.7 on 2018-09-10 05:09

from django.db import migrations, models
import django.db.models.deletion
import permissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('projects', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StmUserPermission',
            fields=[
                ('id', models.CharField(default=permissions.models.generate_guid, max_length=32, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'db_table': 'stm_user_permissions',
            },
        ),
    ]
