# Generated by Django 2.0.7 on 2018-09-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_acceptance_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acceptance',
            new_name='Permission',
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
    ]
