# Generated by Django 2.0.7 on 2018-09-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('permissions', '0003_auto_20180918_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False, verbose_name='Active / Inactive')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.PermissionT')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Active / Inactive')),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active / Inactive'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to='permissions.Role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role'),
        ),
        migrations.AddField(
            model_name='permissiont',
            name='roles',
            field=models.ManyToManyField(editable=False, related_name='permissions', through='permissions.RolePermission', to='permissions.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(editable=False, related_name='roles', through='permissions.UserRole', to='users.UserProfile'),
        ),
    ]
