# Generated by Django 2.0.7 on 2018-09-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20180918_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiont',
            options={'verbose_name': 'Permission'},
        ),
    ]
