# Generated by Django 2.0.7 on 2018-09-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_auto_20180920_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='task',
        ),
    ]
