# Generated by Django 2.0.7 on 2018-09-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_remove_role_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.Organization'),
        ),
    ]
