# Generated by Django 2.0.7 on 2018-09-10 05:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=tasks.models.generate_guid, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disputed', 'Disputed')], default='open', max_length=8)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('project_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('assignee_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('assigned_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting'), ('call', 'Call')], default='task', max_length=8)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
